### ISSUE TITLE
The `writtenSize` value passed as a reference is returned as function return value

### ISSUE THREAD

**Issue by mateusz-plociennik** [mmomtchev/swig#61]
I have the following code:
```cpp
class DisplayServer
{
public:
	void dumpFrame(uint32_t displayIndex, void* buffer, uint32_t size, uint32_t& writtenSize) { writtenSize = 123; }
};
```
that I wrap with:
```swig
%module rpc

%include <arraybuffer.i>
%include <stdint.i>
%include <stl.i>
%include <typemaps.i>

%apply uint32_t& INOUT { uint32_t& writtenSize };

%typemap(in)        (void* buffer, uint32_t size) = WRITABLE_BUFFER_SIGNATURE;
%typemap(typecheck) (void* buffer, uint32_t size) = WRITABLE_BUFFER_SIGNATURE;
```
and execute:
```js
var displayServer = new rpc.DisplayServer
var displayIndex = 0;
var png = new ArrayBuffer(1e6, { maxByteLength: 1e6 });
var writtenSize = 0;
displayServer.dumpFrame(displayIndex, png, writtenSize);
console.log(`writtenSize: ${writtenSize}`);
```
The problem I am having is that `writtenSize` on JS side equals `0`, despite being updated on CPP side.
What I have noticed is that the function returns the actual `writtenSize` as function return.
So if I update the JS code to `writtenSize = displayServer.dumpFrame(displayIndex, png, 0);` I get `123`.

Is that the expected behaviour of Napi?

**Comment by mmomtchev** [comment]
Yes. JavaScript - as many other similar languages - cannot pass a scalar value by reference. Scalar values are always passed by value. 

In SWIG, there is an `INOUT` unit test that uses an array that works - because arrays are passed by reference. However, there is no way to access the variable that holds the `writtenSize` value inside the `dumpFrame` function - no matter if this function is implemented in C++ or JavaScript.

This is a fundamental JavaScript limitation.
